services:
  nginx:
    build: ./backend/nginx
    ports: ["8080:80"]
    depends_on: [backend]
    networks:
      - app-network
  backend:
    build: ./backend
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-1.5-flash}
      EXCHANGERATE_API_KEY: ${EXCHANGERATE_API_KEY}
      FRONTEND_ORIGIN: http://localhost:3000
      PORT: 5001
      REDIS_URL: redis://redis:6379/0
      GRPC_VERBOSITY: ERROR
      GLOG_minloglevel: 2
    ports: ["5001:5001"]
    depends_on: [redis]
    volumes:
      - ./backend:/app
    command: python app.py
    networks:
      - app-network
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
    ports: ["3000:3000"]
    depends_on: [backend]
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
